version: '3.8'
services:
  skillsprint:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - PORT=5000
    volumes:
      - ./backend/uploads:/app/backend/uploads
